### ISSUE TITLE
Open discussion for next beta feature planning (please comment!)

### ISSUE THREAD

**Issue by nvll** [nvll/xivtools#28]
Right now I'm working on the following:
- Moving crafting to the gui entirely with progress bars for status
- Teamcraft list imports from the clipboard
- Re-enabling role actions

I have some preliminary research for for features that will require memory reading, but I'm not prioritizing it for now. I would love to know specifically what issues folks are having, what they wish they could do, and generally how satisfied users are.

**Comment by mmaine** [comment]
Something I'd like to see(haven't thought the fine details out yet) is to set specific macros for specific rlvl. In combination of teamcraft list import instead of having to specify every item a macro themselves, a universal list for specific rlvl (with option to override macro obviously) could be something to consider for future. Also for whether specialist or not.

ie. When Dwarven Mythril Ingot is added, the rlvl/dur is taken and the macro specific for x dur/rlvl is automatically applied onto it. Not sure how feasible it is to implement, but would be something that can significantly reduce setup time after an initial setup.

**Comment by mmaine** [comment]
On larger lists, sometimes you want to stop halfway through a craft. Would it be possible to have every step that completes reduce a craft?

For example:
Crafting 10 crafter sets, but only managing to do 5 crafts before you realize you need to repair. You stop, but then have to manually check which items were done and reduce them from the list itself. Is it possible to automate this process?

Hope I'm being clear enough

**Comment by nvll** [comment]
I've thought about it a bit, but I'm not sure how the UI flow should work in case you want to stop because Talan was having a problem and you don't know how much it successfully crafted.
