### ISSUE TITLE
rlvl_max seemingly not recognized?

### ISSUE THREAD

**Issue by mmaine** [nvll/xivtools#35]
> #100% HQ any 1-50 Item
[[xiv_macro]]
name = "1 - 50 HQ"
rlvl_max = 50
durability = [ 35, 40, 60, 70, 80 ]
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
""

Is being selected instead of:

>[[xiv_macro]]
name = "2* 70d Foodless"
durability = [ 70 ]
difficulty= 5645
actions = """
/ac Reflect <wait.3>
/ac Manipulation <wait.2>
/ac Ingenuity <wait.2>
/ac "Delicate Synthesis" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Great Strides" <wait.2>
/ac Ingenuity <wait.2>
/ac "Preparatory Touch" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Byregot's Blessing" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""

for 5645 durability items (2* recipes, ie. current food and potions).
https://i.imgur.com/AXb9rSq.png

**Comment by nvll** [comment]
Could you paste/attach your full macros.toml and config.json?

**Comment by mmaine** [comment]
macros.toml: https://pastebin.com/Ri5SEe1V
config.json: https://pastebin.com/PXdzAFBU

i've commented out the 1-50 macro in the macros.toml, and I at least couldn't see any reason why it would overwrite it. There's always the likelyhood of me missing something really obvious.

**Comment by nvll** [comment]
The issue is that in the example I wrote the wrong field for rlvl. The correct fields are:
max_rlvl
min_rlvl

The 1-50 HQ macro is matching because the only field it has is the durability which is matched against the recipe's 70 durability.

I'll correct the example and see if I can make an error occur when unrecognized fields are found, rather than ignoring them.

**Comment by nvll** [comment]
Updated in 0.4.2.
